import {act as actIos} from '../skills/delivery/jev-ui/scripts/ios.mjs';
import {runAcceptance,parseArgs,stopNativeFixture} from '../skills/delivery/jev-ui/scripts/acceptance.mjs';
import {EventEmitter} from 'node:events';
const fakeChild = result => { const child = new EventEmitter(); child.stdout = new EventEmitter(); child.stderr = new EventEmitter(); queueMicrotask(() => { if (result.stdout !== undefined) child.stdout.emit('data', result.stdout); if (result.stderr !== undefined) child.stderr.emit('data', result.stderr); child.emit('close', result.code ?? null, result.signal ?? null); }); return child; };
import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
test('missing optional record-evidence integration is blocked',async()=>{const result=await runAcceptance({config:{surface:'browser',expected:'Confirmed'}});assert.equal(result.status,'blocked');assert.match(result.reason,/record-evidence/);});
test('rejected recorder start does not mutate pre-existing evidence or stop',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jev-recorder-reject-'));const receipt=path.join(dir,'jev-receipt.json'),media=path.join(dir,'evidence.mp4');fs.writeFileSync(receipt,'old receipt\n');fs.writeFileSync(media,Buffer.from('old media'));const before=[fs.readFileSync(receipt),fs.readFileSync(media)];let stops=0;const result=await runAcceptance({config:{surface:'browser',expected:'Confirmed',evidenceDir:dir},recorder:{start:async()=>{throw Error('session already exists')},stop:async()=>{stops++}},controller:async()=>{throw Error('must not run')}});assert.equal(result.status,'blocked');assert.equal(stops,0);assert.deepEqual(fs.readFileSync(receipt),before[0]);assert.deepEqual(fs.readFileSync(media),before[1]);assert.equal(fs.readdirSync(dir).sort().join(','),'evidence.mp4,jev-receipt.json');});
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {run, consumeDecision, verifyPostconditions, configuredHelper, independentPostconditions, closeOwnedBrowser} from '../skills/delivery/jev-ui/scripts/jev-ui.mjs';
import {buildRequest, validateAnswers, choose as chooseTypesafeRequest} from '../skills/delivery/jev-ui/scripts/typesafe.mjs';
import {stableIdentity} from '../skills/delivery/jev-ui/scripts/acceptance.mjs';
test('CLI cleanup closes only its owned browser and reports cleanup failures',async()=>{let browserClosed=0,nativeClosed=0;assert.equal(await closeOwnedBrowser({close:async()=>{browserClosed++;}},'browser'),null);assert.equal(browserClosed,1);assert.equal(await closeOwnedBrowser({close:async()=>{nativeClosed++;}},'android'),null);assert.equal(nativeClosed,0);const cleanupError=await closeOwnedBrowser({close:async()=>{throw Error('close failed');}},'browser');assert.match(cleanupError.message,/close failed/);});
test('TypeSafe chooser receives bounded action outcomes without payloads',async()=>{let request;const result=await chooseTypesafeRequest({goal:'set Name',snapshot:{elements:[{id:'name',name:'Name',operations:['TYPE_TEXT']}]},recentActions:[{operation:'TYPE_TEXT',target:'name',changed:false,raw:'helper-private'}],systemOne:async value=>{request=value;return{operation:'DONE',model:'jev-test',usage:{total_tokens:1}}}});assert.equal(result.decision.operation,'DONE');assert.deepEqual(request.state.recentActions,[{operation:'TYPE_TEXT',target:'name',changed:false}]);assert.doesNotMatch(JSON.stringify(request),/helper-private/);});
test('ambiguous editable equality is visible but not established in the indexed chooser',()=>{
  const snapshot={surface:'android',elements:[{id:'name',name:'Name',value:'Name',valueAmbiguous:true,editable:true,operations:['TYPE_TEXT']},{id:'confirm',name:'Confirm',editable:false,operations:['TAP']}]};
  const request=buildRequest({goal:'Set Name to exactly Name, then tap Confirm',expected:['Confirmed Name'],snapshot});
  assert.equal(request.state.observation.elements[0].value,'Name');
  assert.deepEqual(request.questions.operation.choices,['TYPE_TEXT','TAP','DONE']);
  assert.deepEqual(request.questions.type_text_target.choices,['name']);
  assert.match(request.questions.type_text_target.criteria.name,/ambiguous/);
  assert.match(request.questions.type_text_target.criteria.name,/not be treated as established/);
  assert.doesNotMatch(JSON.stringify(request),/helper-private|raw-driver/);
  const ordinary=buildRequest({goal:'Use the current Name value',snapshot:{elements:[{id:'name',name:'Name',value:'Name',editable:true,operations:['TYPE_TEXT']}]}});
  assert.doesNotMatch(ordinary.questions.type_text_target.criteria.name,/ambiguous/);
});
test('operation choice is grounded in ambiguity and current DONE facts',()=>{const snapshot={surface:'android',elements:[{id:'name',name:'Name',value:'Name',valueAmbiguous:true,editable:true,operations:['TYPE_TEXT']},{id:'confirm',name:'Confirm',editable:false,operations:['TAP']},{id:'status',name:'Status',value:'Ready for confirmation.',editable:false,operations:[]}]};const request=buildRequest({goal:'Set Name to exactly Name, select Email, confirm once',expected:['Confirmed Name via Email.'],snapshot});assert.match(request.questions.operation.criteria.TYPE_TEXT,/ambiguous editable values/);assert.match(request.questions.operation.criteria.TYPE_TEXT,/operation that can establish/);assert.match(request.questions.operation.criteria.TAP,/cannot establish the ambiguous requested text/);assert.match(request.questions.operation.criteria.DONE,/independently visible now: no/);assert.match(request.questions.operation.criteria.TAP,/Current facts:/);});
test('successful text action metadata resolves label ambiguity without forcing an action',()=>{const snapshot={elements:[{id:'name',name:'Name',value:'Name',valueAmbiguous:true,editable:true,operations:['TYPE_TEXT']},{id:'confirm',name:'Confirm',editable:false,operations:['TAP']}]};const request=buildRequest({goal:'Set Name to exactly Name, then tap Confirm',expected:['Confirmed Name'],snapshot,recentActions:[{operation:'TYPE_TEXT',target:'name',changed:true}]});assert.doesNotMatch(request.questions.operation.criteria.TYPE_TEXT,/operation that can establish/);assert.match(request.questions.operation.criteria.TYPE_TEXT,/recent text action changed/);assert.doesNotMatch(request.questions.type_text_target.criteria.name,/must not be treated as established/);assert.match(request.questions.operation.criteria.TAP,/Perform TAP/);});
test('attempted unchanged text action permits the next confirmation action',()=>{const snapshot={elements:[{id:'name',name:'Name',value:'Name',valueAmbiguous:true,editable:true,operations:['TYPE_TEXT']},{id:'confirm',name:'Confirm',editable:false,operations:['TAP']}]};const request=buildRequest({goal:'Set Name to exactly Name, then tap Confirm',expected:['Confirmed Name'],snapshot,recentActions:[{operation:'TYPE_TEXT',target:'name',changed:false}]});assert.doesNotMatch(request.questions.operation.criteria.TYPE_TEXT,/operation that can establish/);assert.match(request.questions.operation.criteria.TYPE_TEXT,/recent text action was attempted/);assert.doesNotMatch(request.questions.type_text_target.criteria.name,/must not be treated as established/);});
test('ordinary native text entry keeps WAIT available while ambiguity repair removes it only when relevant',()=>{
  const ordinary=buildRequest({goal:'Enter a value and wait for the result',snapshot:{elements:[{id:'entry',name:'Entry',editable:true,value:'old',operations:['TYPE_TEXT','WAIT']},{id:'confirm',name:'Confirm',operations:['TAP']}]},recentActions:[{operation:'TYPE_TEXT',target:'entry',changed:true}]});
  assert.ok(ordinary.questions.operation.choices.includes('WAIT'));
  const equal=buildRequest({goal:'Set Name to exactly Name, then tap Confirm',expected:['Confirmed Name'],snapshot:{elements:[{id:'name',name:'Name',value:'Name',valueAmbiguous:true,editable:true,operations:['TYPE_TEXT','WAIT']},{id:'confirm',name:'Confirm',operations:['TAP']}]}});
  assert.equal(equal.questions.operation.choices.includes('WAIT'),false);
});
test('iOS post-text confirmation does not offer WAIT while Android retains it',()=>{
  const snapshot={surface:'ios',elements:[{id:'name',name:'Name',value:'Casey',valueAmbiguous:true,editable:true,operations:['TYPE_TEXT','WAIT']},{id:'confirm',name:'Confirm',operations:['TAP']} ]};
  const request=buildRequest({goal:'Replace Casey with Jordan, then tap Confirm',expected:['Confirmed Jordan'],snapshot,recentActions:[{operation:'TYPE_TEXT',target:'name',changed:true}]});
  assert.equal(request.questions.operation.choices.includes('WAIT'),false);
  const android=buildRequest({...request.state,snapshot:{...snapshot,surface:'android'}});
  assert.equal(android.questions.operation.choices.includes('WAIT'),true);
});
test('chooser completion facts require every trimmed nonblank outcome on non-editable controls',()=>{const snapshot={elements:[{id:'status',role:'status',value:'Confirmed Name',operations:[]},{id:'email',role:'status',value:'Confirmed Email',operations:[]}]};const request=buildRequest({goal:'confirm',expected:['  Confirmed Name  ','Confirmed Email'],snapshot});assert.match(request.questions.operation.criteria.DONE,/independently visible now: yes/);const missing=buildRequest({goal:'confirm',expected:['Confirmed Name','Missing'],snapshot});assert.match(missing.questions.operation.criteria.DONE,/independently visible now: no/);const blank=buildRequest({goal:'confirm',expected:[' '],snapshot});assert.match(blank.questions.operation.criteria.DONE,/independently visible now: no/);const roleOnly={elements:[{id:'name',role:'android.widget.EditText',value:'Confirmed',operations:['TYPE_TEXT']}]};const roleRequest=buildRequest({goal:'confirm',expected:['Confirmed'],snapshot:roleOnly});assert.match(roleRequest.questions.operation.criteria.DONE,/independently visible now: no/);const inputRoleOnly={elements:[{id:'name',role:'textbox',editable:false,value:'Confirmed',operations:[]}]};const inputRoleRequest=buildRequest({goal:'confirm',expected:['Confirmed'],snapshot:inputRoleOnly});assert.match(inputRoleRequest.questions.operation.criteria.DONE,/independently visible now: no/);const mixed={elements:[{id:'status',role:'status',value:'Confirmed Name',operations:[]},{id:'email',role:'textbox',editable:false,value:'Confirmed Email',operations:[]}]};const mixedRequest=buildRequest({goal:'confirm',expected:['Confirmed Name','Confirmed Email'],snapshot:mixed});assert.match(mixedRequest.questions.operation.criteria.DONE,/independently visible now: no/);});
test('affirmative outcome contract rejects negated and punctuated negatives',()=>{assert.equal(verifyPostconditions(['Confirmed'],'Never Confirmed.'),false);assert.equal(verifyPostconditions(['Confirmed'],'Not yet Confirmed!'),false);assert.equal(verifyPostconditions(['Confirmed'],'Confirmed, not actually complete.'),false);assert.equal(verifyPostconditions(['Confirmed'],'Confirmed.'),true);assert.equal(verifyPostconditions(['Confirmed Name'],'Confirmed Name via Email.'),true);});
test('typesafe and controller modules initialize without a cycle',async()=>{const controller=await import('../skills/delivery/jev-ui/scripts/jev-ui.mjs');const typesafe=await import('../skills/delivery/jev-ui/scripts/typesafe.mjs');assert.equal(typeof controller.run,'function');assert.equal(typeof typesafe.buildRequest,'function');});
test('aliased first text action is attempted before unchanged-action bound',async()=>{let actions=0;let choices=0;const snapshot=makeSnapshot({target:'s1',raw:'same',elements:[{id:'name',role:'textbox',name:'Name',value:'Name',operations:['FILL']}]});const r=await run({goal:'set Name',expectedPostconditions:['Confirmed'],session,adapter:{observe:async()=>snapshot,act:async()=>{actions++;return {ok:true}}},chooser:async()=>{choices++;return{decision:{operation:'FILL',target:'name'},model:'m',usage:{}}},textHelper:async()=>({text:'Name'}),limits:{maxActions:5,maxModels:5}});assert.equal(r.status,'blocked');assert.equal(actions,3);assert.equal(choices,3);assert.match(r.reason,/repeated/);});
test('recent action metadata is bounded and excludes raw text',()=>{const request=buildRequest({goal:'set Name',snapshot:{elements:[]},recentActions:[{operation:'TYPE_TEXT',target:'name',changed:false,raw:'secret-value'},{operation:'TAP',target:'confirm',changed:true},{operation:'WAIT',target:'x',changed:false},{operation:'TYPE_TEXT',target:'name',changed:true}]});assert.deepEqual(request.state.recentActions,[{operation:'TAP',target:'confirm',changed:true},{operation:'WAIT',target:'x',changed:false},{operation:'TYPE_TEXT',target:'name',changed:true}]);assert.doesNotMatch(JSON.stringify(request),/secret-value/);});
test('fresh ordinary values remain visible while raw helper payloads stay absent',async()=>{let calls=0;const seen=[];const initial=makeSnapshot({target:'s1',raw:'initial',elements:[{id:'name',role:'textbox',name:'Name',value:'',operations:['FILL']}]});const after=makeSnapshot({target:'s1',raw:'ordinary UI text',elements:[{id:'name',role:'textbox',name:'Name',value:'ordinary-marker',operations:['FILL']} ]});const result=await run({goal:'set Name',expectedPostconditions:['Confirmed'],session,adapter:{observe:async()=>calls++?after:initial,act:async()=>{}},chooser:async input=>{seen.push(input.snapshot);return calls===1?{decision:{operation:'FILL',target:'name'},model:'m',usage:{}}:{decision:{operation:'DONE'},model:'m',usage:{}}},textHelper:async()=>({text:'helper-private'}),limits:{maxActions:2,maxModels:2}});assert.equal(result.status,'failed');assert.equal(seen.length,2);assert.equal(seen[0].elements[0].value,'');assert.equal(seen[1].elements[0].value,'ordinary-marker');assert.doesNotMatch(JSON.stringify(seen[1]),/helper-private/);});
import {makeSnapshot, normalizeSnapshot, cdpOriginGuard, assertOrigin} from '../skills/delivery/jev-ui/scripts/browser.mjs';
test('full origin rejects unrelated host, scheme, and port',()=>{assertOrigin('https://app.test/path','https://app.test');assert.throws(()=>assertOrigin('http://app.test','https://app.test'),/left the selected origin/);assert.throws(()=>assertOrigin('https://other.test','https://app.test'),/left the selected origin/);assert.throws(()=>assertOrigin('https://app.test:8443','https://app.test'),/left the selected origin/);});
class GuardSocket {
  static last;
  constructor() { this.listeners = {}; this.commands = []; this.closed = false; GuardSocket.last = this; queueMicrotask(() => this.emit('open')); }
  addEventListener(type, fn) { (this.listeners[type] ??= []).push(fn); }
  emit(type, data) { for (const fn of this.listeners[type] ?? []) fn({data: JSON.stringify(data)}); }
  send(raw) {
    const message = JSON.parse(raw);
    this.commands.push(message);
    const result = message.method === 'Target.getTargets' ? {targetInfos: [{targetId: 'page-1', type: 'page', attached: false}]} : {};
    queueMicrotask(() => {
      this.emit('message', {id: message.id, result});
      if (message.method === 'Target.attachToTarget') this.emit('message', {method: 'Target.attachedToTarget', params: {sessionId: 'session-1', targetInfo: {targetId: 'page-1'}}});
    });
  }
  close() { this.closed = true; }
}
const waitFor = async (predicate) => { for (let i = 0; i < 20; i++) { if (predicate()) return; await new Promise(resolve => setTimeout(resolve, 0)); } throw new Error('timed out waiting for CDP command'); };
test('origin guard fails unauthorized requests and continues authorized requests',async()=>{
  const guard = await cdpOriginGuard('ws://owned','https://app.test',{WebSocketImpl:GuardSocket});
  const socket = GuardSocket.last;
  await waitFor(() => socket.commands.some(command => command.method === 'Fetch.enable'));
  const fetchIndex=socket.commands.findIndex(command=>command.method==='Fetch.enable'); const resumeIndex=socket.commands.findIndex(command=>command.method==='Runtime.runIfWaitingForDebugger'); assert.ok(fetchIndex>=0 && resumeIndex>fetchIndex);
  socket.emit('message',{method:'Fetch.requestPaused',sessionId:'session-1',params:{requestId:'blocked',request:{url:'https://other.test/redirect'}}});
  socket.emit('message',{method:'Fetch.requestPaused',sessionId:'session-1',params:{requestId:'allowed',request:{url:'https://app.test/next'}}});
  await waitFor(() => socket.commands.some(command => command.method === 'Fetch.failRequest' && command.params.requestId === 'blocked'));
  await waitFor(() => socket.commands.some(command => command.method === 'Fetch.continueRequest' && command.params.requestId === 'allowed'));
  await guard.close(); assert.equal(socket.closed,true);
});
test('closed transport cleanup is idempotent and does not await disable',async()=>{const guard=await cdpOriginGuard('ws://owned','https://app.test',{WebSocketImpl:GuardSocket});const socket=GuardSocket.last;socket.emit('close');await Promise.race([guard.close(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('cleanup hung')),100))]);await guard.close();});
test('secret-like visible values are omitted before model observation',()=>{const snapshot=makeSnapshot({target:'s1',raw:'API token\nsecret-value\nSubmit',elements:[{id:'token',name:'API token',role:'textbox',value:'secret-value',operations:['FILL']},{id:'submit',name:'Submit',operations:['CLICK']}]});assert.equal(snapshot.elements[0].value,undefined);assert.doesNotMatch(snapshot.text,/secret-value/);assert.equal(snapshot.elements[1].name,'Submit');});
test('secret-like values are removed from raw observations even on separate lines',()=>{const snapshot=makeSnapshot({target:'s1',raw:'API token\nopaque-value\nSubmit',elements:[{id:'token',name:'API token',role:'textbox',value:'opaque-value',operations:['FILL']},{id:'submit',name:'Submit',operations:['CLICK']}]});assert.doesNotMatch(snapshot.text,/opaque-value/);});
const session={id:'s1'};
function adapter({stale=false}={}) { let n=0, mutations=0; return {get mutations(){return mutations}, observe: async()=>makeSnapshot({target:'s1',elements:[{id:'e1',name:'Button',operations:['click']}],raw:stale?String(n++):'same'}), act: async()=>{mutations++; return {ok:true}}}; }
const choose=(decision)=>async()=>({decision,model:'m',usage:{total_tokens:1}});
test('invalid target is rejected without adapter mutation',async()=>{const a=adapter();const r=await run({goal:'x',session,adapter:a,chooser:choose({operation:'click',target:'bad'})});assert.equal(a.mutations,0);assert.equal(r.status,'failed');});
test('editable Android value cannot satisfy independent output assertion',()=>{const snapshot={surface:'android',elements:[{id:'name',role:'android.widget.EditText',editable:true,value:'Confirmed',operations:['TYPE_TEXT']},{id:'status',role:'android.widget.TextView',editable:false,value:'Ready for confirmation.',operations:[]}]};assert.deepEqual(independentPostconditions(['Confirmed'],snapshot),[]);});
test('execution narration precedes the next observation and carries safe metadata',async()=>{const order=[];let observations=0;const snap=()=>({target:{id:'s1'},elements:[{id:'button',name:'Confirm',operations:['TAP']},{id:'status',role:'status',value:observations>1?'Confirmed':'Ready',operations:[]}]});const result=await run({goal:'confirm',expectedPostconditions:['Confirmed'],session:{id:'s1'},adapter:{observe:async()=>{order.push('observe');observations++;return snap()},act:async()=>{order.push('driver');return{ok:true}}},chooser:async()=>observations===1?{decision:{operation:'TAP',target:'button'},model:'m',usage:{}}:{decision:{operation:'DONE'},model:'m',usage:{}},onExecution:async execution=>{order.push(['narrate',execution.operation,execution.target,execution.ok]);assert.equal(Object.hasOwn(execution,'text'),false)}});assert.equal(result.status,'passed');assert.deepEqual(order,['observe','driver',['narrate','TAP','button',true],'observe','observe']);});
test('DONE requires independent postcondition observation',async()=>{const a=adapter();const r=await run({goal:'x',expectedPostconditions:['Confirmation'],session,adapter:a,chooser:choose({operation:'DONE'})});assert.equal(r.status,'failed');assert.equal(a.mutations,0);});
test('public DONE cannot pass from editable self-echo',async()=>{const snapshot=makeSnapshot({target:'s1',elements:[{id:'name',role:'textbox',name:'Name',value:'Confirmed',operations:['FILL']},{id:'status',role:'status',name:'Status',value:'Ready for confirmation.',operations:[]}]});const r=await run({goal:'confirm',expectedPostconditions:['Confirmed'],session,adapter:{observe:async()=>snapshot,act:async()=>({})},chooser:choose({operation:'DONE'})});assert.equal(r.status,'failed');assert.match(r.reason,/independently/);});
test('action budget is blocked',async()=>{const a=adapter();const r=await run({goal:'x',session,adapter:a,chooser:choose({operation:'click',target:'e1'}),limits:{maxActions:1,maxModels:5}});assert.equal(r.status,'blocked');assert.match(r.reason,/budget/);});
test('one-time decision consumption and postcondition helper',()=>{const state={consumed:false};consumeDecision(state,{operation:'click'});assert.throws(()=>consumeDecision(state,{}),/already/);assert.equal(verifyPostconditions(['Done'],'done now'),true);});
test('DONE without a non-empty independent assertion never passes',async()=>{const a=adapter();const r=await run({goal:'x',session,adapter:a,expectedPostconditions:[],chooser:choose({operation:'DONE'})});assert.equal(r.status,'failed');assert.match(r.reason,/not observed/);assert.equal(verifyPostconditions(['  '],'anything'),false);});
test('explicit zero action budget is honored',async()=>{const a=adapter();const r=await run({goal:'x',session,adapter:a,chooser:choose({operation:'click',target:'e1'}),limits:{maxActions:0,maxModels:5}});assert.equal(r.status,'blocked');assert.match(r.reason,/action budget/);assert.equal(a.mutations,0);});
test('generic CLI accepts configured text helper commands',()=>{const before=process.env.JEV_UI_TEXT_HELPER;try{process.env.JEV_UI_TEXT_HELPER='["node","-e","console.log()"]';assert.deepEqual(configuredHelper(),['node','-e','console.log()']);process.env.JEV_UI_TEXT_HELPER='{"program":"node","args":["-e","console.log()"]}';assert.deepEqual(configuredHelper(),['node','-e','console.log()']);}finally{if(before===undefined)delete process.env.JEV_UI_TEXT_HELPER;else process.env.JEV_UI_TEXT_HELPER=before;}});
test('malformed and incompatible TypeSafe choices are rejected',()=>{const s=makeSnapshot({target:'s1',elements:[{id:'e1',operations:['click']}]});assert.throws(()=>validateAnswers({operation:{choice:'click',probabilities:{click:2}},target:'e1'},s));assert.throws(()=>validateAnswers({operation:'fill',target:'e1'},s));});
test('stale adapter failure remains non-green',async()=>{const a=adapter();const r=await run({goal:'x',session,adapter:{observe:a.observe,act:async()=>{throw Object.assign(new Error('observation is stale'),{code:'stale-observation'})}},chooser:choose({operation:'click',target:'e1'})});assert.equal(r.status,'failed');});
test('unknown answer fields are rejected without mutation',()=>{const s=makeSnapshot({target:'s1',elements:[{id:'e1',operations:['click']}]});assert.throws(()=>validateAnswers({operation:'click',click_target:'e1',selector:'#unsafe'},s),/unexpected answer field/);});
test('SELECT requires and preserves an observed value',()=>{const s=makeSnapshot({target:'s1',elements:[{id:'e1',role:'combobox',value:'red',operations:['SELECT']}]});assert.deepEqual(validateAnswers({operation:'SELECT',target:'e1',select_value:'red'},s),{operation:'SELECT',target:'e1',value:'red'});assert.throws(()=>validateAnswers({operation:'SELECT',target:'e1'},s),/observed value/);assert.throws(()=>validateAnswers({operation:'SELECT',target:'e1',select_value:'blue'},s),/observed value/);});
test('SELECT executes the current observed option on a non-fixture control',async()=>{const observed=makeSnapshot({target:'s1',elements:[{id:'country',ref:'4',role:'combobox',options:[{value:'ca',label:'Canada'},{value:'us',label:'United States'}],operations:['SELECT']}]}); let selected; const r=await run({goal:'choose Canada',session,adapter:{observe:async()=>observed,act:async(_session,_snapshot,action)=>{selected=action;return {ok:true}}},chooser:choose({operation:'SELECT',target:'country',value:'ca'}),limits:{maxActions:1,maxModels:1}}); assert.equal(selected.value,'ca'); assert.equal(r.status,'blocked'); assert.deepEqual(normalizeSnapshot({elements:[{id:'country',role:'combobox',options:[{value:'ca',label:'Canada'}],operations:['SELECT']}]},'s1').elements[0].options[0].value,'ca');});
test('invalid finite budgets are blocked before observation',async()=>{let observed=0;const r=await run({goal:'x',session,adapter:{observe:async()=>{observed++;return makeSnapshot({target:'s1'})}},limits:{maxActions:Infinity}});assert.equal(r.status,'blocked');assert.equal(observed,0);});
test('iOS cleanup rejects unreadable app-state and accepts valid stopped observations',async()=>{
  const prior=process.env.IDB_COMPANION; process.env.IDB_COMPANION='/tmp/test-companion';
  try {
    let calls=[]; let results=[{code:0,stdout:''}];
    await assert.rejects(()=>stopNativeFixture('ios','sim',{spawnImpl:(command,args)=>{calls.push(command);return fakeChild(results.shift());}}),/unusable/);
    assert.deepEqual(calls,['idb']);
    calls=[]; results=[{code:0,stdout:'[]'}];
    assert.deepEqual(await stopNativeFixture('ios','sim',{spawnImpl:(command,args)=>{calls.push(command);return fakeChild(results.shift());}}),{stopped:true,verified:true});
    assert.deepEqual(calls,['idb']);
    calls=[]; results=[{code:0,stdout:'[{"bundle_id":"ai.typesafe.jevfixture","process_state":"Unknown","pid":null}]'}];
    assert.deepEqual(await stopNativeFixture('ios','sim',{spawnImpl:(command,args)=>{calls.push(command);return fakeChild(results.shift());}}),{stopped:true,verified:true});
    assert.deepEqual(calls,['idb']);
    calls=[]; results=[{code:0,stdout:'[{"bundle_id":"ai.typesafe.jevfixture","process_state":"Running"}]'},{code:null,signal:'SIGTERM',stderr:'terminated'},{code:0,stdout:''}];
    await assert.rejects(()=>stopNativeFixture('ios','sim',{spawnImpl:(command,args)=>{calls.push(command);return fakeChild(results.shift());}}),/unusable/);
    assert.deepEqual(calls,['idb','xcrun','idb']);
  } finally { if(prior===undefined) delete process.env.IDB_COMPANION; else process.env.IDB_COMPANION=prior; }
});
test('iOS cleanup rejects parsed but unusable app-state records',async()=>{
  const prior=process.env.IDB_COMPANION; process.env.IDB_COMPANION='/tmp/test-companion';
  try {
    for(const stdout of ['{}','{"error":"service unavailable"}','[{"bundle_id":"ai.typesafe.jevfixture","pid":12}]']) {
      await assert.rejects(()=>stopNativeFixture('ios','sim',{spawnImpl:()=>fakeChild({code:0,stdout})}),/unusable/);
    }
  } finally { if(prior===undefined) delete process.env.IDB_COMPANION; else process.env.IDB_COMPANION=prior; }
});
test('iOS TYPE_TEXT dispatches to the revalidated focused frame',async()=>{
  const prior=process.env.IDB_COMPANION; process.env.IDB_COMPANION='/tmp/test-companion';
  try {
    const identity={id:'sim',app:'ai.typesafe.jevfixture',driver:'idb',pid:12,verifyDevice:false};
    const snapshot={target:{id:'sim',app:identity.app,driver:'idb',pid:12},elements:[{id:'native-0',name:'Name',pid:12,editable:true,focused:false,value:'Casey',frame:{x:11,y:7},operations:['TYPE_TEXT']}]};
    let observations=0; const focused={...snapshot,elements:[{...snapshot.elements[0],focused:true,frame:{x:109,y:93}}]};
    let calls=[]; const runner=async(command,args)=>{calls.push([command,args]);return {stdout:'',stderr:''};};
    await actIos(identity,snapshot,{operation:'TYPE_TEXT',target:'native-0',text:'Jordan'},{runner,observe:async()=>{observations++; return observations>2?{...focused,elements:[{...focused.elements[0],value:'Jordan'}]}:focused;}});
    const setValue=calls.find(([,args])=>args.includes('set-value'))[1];
    assert.equal(setValue[setValue.indexOf('--value')+4],'109');
    assert.equal(setValue[setValue.indexOf('--value')+5],'93');
  } finally { if(prior===undefined) delete process.env.IDB_COMPANION; else process.env.IDB_COMPANION=prior; }
});
test('repeated unchanged actions are blocked',async()=>{let actions=0;const snapshot=makeSnapshot({target:'s1',raw:'same',elements:[{id:'button',role:'button',name:'Confirm',operations:['CLICK']}]});const r=await run({session,adapter:{observe:async()=>snapshot,act:async()=>actions++},chooser:async()=>({decision:{operation:'CLICK',target:'button'},model:'m',usage:{}}),limits:{maxActions:5,maxModels:5}});assert.equal(r.status,'blocked');assert.equal(actions,3);assert.match(r.reason,/repeated/);});
test('later chooser requests retain ordinary values from fresh authorized observations',async()=>{const seen=[];let observations=0;const snapshot=()=>makeSnapshot({target:'s1',elements:[{id:'name',role:'textbox',name:'Name',value:observations?'ordinary-marker':'',operations:['FILL']},{id:'done',role:'status',name:'Status',value:'Confirmed',operations:[]}]});const r=await run({goal:'fill',expectedPostconditions:['Confirmed'],session,adapter:{observe:async()=>{observations++;return snapshot()},act:async()=>({ok:true})},chooser:async request=>{seen.push(request.snapshot.elements.find(e=>e.id==='name')?.value);return seen.length===1?{decision:{operation:'FILL',target:'name'},model:'m',usage:{}}:{decision:{operation:'DONE'},model:'m',usage:{}}},textHelper:async()=>({text:'helper-private'})});assert.equal(r.status,'passed');assert.deepEqual(seen,['ordinary-marker','ordinary-marker']);assert.ok(!seen.includes('helper-private'));});
test('later chooser requests omit sensitive native values and raw observations',async()=>{const seen=[];const snapshot={surface:'android',target:{id:'d1'},raw:'driver-private',elements:[{id:'token',role:'EditText',name:'API token',value:'sensitive-private',operations:['TYPE_TEXT']},{id:'status',role:'status',name:'Status',value:'Confirmed',operations:[]}]};const r=await run({goal:'done',expectedPostconditions:['Confirmed'],session:{surface:'android',target:{id:'d1'}},adapter:{observe:async()=>snapshot,act:async()=>({raw:'driver-private'})},chooser:async request=>{seen.push(JSON.stringify(request.snapshot));return seen.length===1?{decision:{operation:'TYPE_TEXT',target:'token'},model:'m',usage:{}}:{decision:{operation:'DONE'},model:'m',usage:{}}},textHelper:async()=>({text:'helper-private'})});assert.equal(r.status,'passed');assert.equal(seen.length,2);for(const payload of seen){assert.doesNotMatch(payload,/sensitive-private|driver-private|helper-private/);}});
test('acceptance defaults retain generic contract and replacement mode requires two goals',()=>{const config=parseArgs([]);assert.equal(config.goal,'Confirm the delivery check-in');assert.equal(config.expected,'Confirmed');assert.equal(config.initialName,undefined);const replacement=parseArgs(['--surface','android','--target','emulator-5560','--seed-goal','seed Casey','--seed-expected','Confirmed Casey','--goal','replace Jordan','--expected','Confirmed Jordan']);assert.equal(replacement.seedGoal,'seed Casey');assert.equal(replacement.seedExpected,'Confirmed Casey');assert.equal(replacement.initialName,undefined);assert.throws(()=>parseArgs(['--surface','android','--target','emulator-5560','--seed-goal','seed Casey']),/supplied together/);assert.throws(()=>parseArgs(['--surface','android','--target','emulator-5560','--seed-goal','seed Casey','--seed-expected','Confirmed Casey','--initial-name','Casey']),/cannot use/);});
test('replacement identity rejects PID drift and accepts omitted receipt fields',()=>{const stable={target:{id:'sim'},observations:[{target:{id:'sim',app:'fixture',pid:10,simulator:true}},{target:{id:'sim',app:'fixture',pid:10,simulator:true}}]};assert.equal(stableIdentity(stable,stable.target),true);const drift={target:{id:'sim'},observations:[{target:{id:'sim',app:'fixture',pid:10,simulator:true}},{target:{id:'sim',app:'fixture',pid:11,simulator:true}}]};assert.equal(stableIdentity(drift,drift.target),false);});
test('acceptance cleanup errors preserve non-green terminal status',async()=>{const result=await runAcceptance({config:{surface:'browser',evidenceDir:'/tmp/jev-cleanup-proof',expected:'Confirmed'},session:{id:'browser',close:async()=>{throw Error('owned close failed')}},recorder:{start:async()=>({session:'/tmp/session'}),annotate:async()=>{},stop:async()=>({verified:true,session:'/tmp/session',manifest:'/tmp/m',report:'/tmp/r',video:'/tmp/v',assertions:{passed:1,failed:0}})},controller:async()=>({status:'passed',target:{id:'browser'},decisions:[{model:'jev-test',usage:{total_tokens:1}}],expectedPostconditions:['Confirmed'],observations:[{target:{id:'browser'},elements:[{role:'status',value:'Confirmed'}]}]}),captureScreenshot:async()=>{},stopFixture:async()=>{}});assert.notEqual(result.status,'passed');});
test('native launch rejection still cleans up the authorized fixture',async()=>{let stopped=0;const result=await runAcceptance({config:{surface:'ios',target:'7A023F51-F0DA-4179-868B-19207E433651',evidenceDir:fs.mkdtempSync(path.join(os.tmpdir(),'jev-launch-reject-')),expected:'Confirmed'},recorder:{start:async()=>({session:'session'}),annotate:async()=>{},stop:async()=>({verified:true,session:'session',manifest:'manifest',report:'report',video:'video',assertions:{passed:0,failed:0}})},launchFixture:async()=>{throw Error('fixture launch failed after setup')},stopFixture:async()=>{stopped++}});assert.equal(result.status,'blocked');assert.match(result.reason,/fixture launch failed after setup/);assert.equal(stopped,2);});
test('failed controller outcome remains failed after owned cleanup',async()=>{let stopped=0;const result=await runAcceptance({config:{surface:'ios',target:'7A023F51-F0DA-4179-868B-19207E433651',evidenceDir:fs.mkdtempSync(path.join(os.tmpdir(),'jev-controller-failed-')),expected:'Confirmed'},recorder:{start:async()=>({session:'session'}),annotate:async()=>{},stop:async()=>({verified:true,session:'session',manifest:'manifest',report:'report',video:'video',assertions:{passed:0,failed:1}})},controller:async()=>({status:'failed',reason:'postcondition not observed',target:{id:'sim'},expectedPostconditions:['Confirmed'],observations:[],decisions:[]}),launchFixture:async()=>({}),stopFixture:async()=>{stopped++},captureScreenshot:async()=>{}});assert.equal(result.status,'failed');assert.match(result.reason,/postcondition not observed/);assert.equal(stopped,2);});
test('origin guard waits for delayed Fetch readiness on initial and popup targets',async()=>{
  class DelayedGuardSocket extends GuardSocket {
    send(raw){
      const message=JSON.parse(raw);
      if(message.method==='Fetch.enable'){
        this.commands.push(message);
        setTimeout(()=>this.emit('message',{id:message.id,result:{}}),25);
        return;
      }
      return super.send(raw);
    }
  }
  const started=Date.now();
  const guard=await cdpOriginGuard('ws://owned','https://app.test',{WebSocketImpl:DelayedGuardSocket});
  const socket=GuardSocket.last;
  assert.ok(Date.now()-started>=20);
  socket.emit('message',{method:'Target.attachedToTarget',params:{sessionId:'popup-session',targetInfo:{targetId:'popup'}}});
  await waitFor(()=>socket.commands.some(command=>command.method==='Fetch.enable'&&command.sessionId==='popup-session'));
  assert.equal(socket.commands.some(command=>command.method==='Runtime.runIfWaitingForDebugger'&&command.sessionId==='popup-session'),false);
  await new Promise(resolve=>setTimeout(resolve,35));
  assert.ok(socket.commands.some(command=>command.method==='Runtime.runIfWaitingForDebugger'&&command.sessionId==='popup-session'));
  await guard.close();
});
